---
name: RSpec Test Suite
on:
- push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: "${{ runner.OS }}-gem-cache-${{ hashFiles('**/database_sanity_checker.gemspec')
          }}"
        restore-keys: "${{ runner.OS }}-gem-cache-\n"
    - name: Install bundler
      run: (bundler -v | grep "2.0.2") || gem install bundler:2.0.2
    - run: mkdir -p ~/.gem
    - run: 'echo "---" > ~/.gem/credentials && echo ":github: Bearer ${{ secrets.TRIKE_DEPLOY_ACCESS_TOKEN
        }}" >> ~/.gem/credentials'
    - run: bundle config https://rubygems.pkg.github.com/tricycle trike-deploy:${{
        secrets.TRIKE_DEPLOY_ACCESS_TOKEN }}
    - name: Install gems
      run: bundle install --jobs $(nproc) --retry 3 --without metrics --path vendor/bundle
    - name: Create cache directory
      run: mkdir -p tmp/cache
    - name: Run RSpec test suite
      run: bundle exec rspec spec
      env:
        METRICS: 1
    - name: Post to Slack if build fails
      if: failure()
      uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"
      with:
        args: '{\"channel\":\"C33574SJJ\",\"text\":\"*BUILD FAILURE*: ${{ github.repository
          }}\n*${{ github.actor }}* made some changes, hoping that they''d pass...
          those changes now are coming back to bite them in the... :boom:\", \"attachments\":
          [{ \"fallback\": \"Failure summary\", \"color\": \"#ff0000\", \"fields\":
          [{ \"title\": \"What broke\", \"value\": \"https://github.com/${{ github.repository
          }}/commit/${{ github.sha }}/checks\", \"short\": false }]}]}'
